### PR TITLE
Fix the DB watch

### PR DESCRIPTION
**Pull request by Alekuso**
RE: PR but this one should fix the issues we have with the websocket and all.

### CODE REVIEW

**Comment by Alekuso** [comment]
Don't merge rn as I'm trying to find a way to not use the `bypassDocumentValidation` option.

**Comment by Alekuso** [comment]
should be good now, can be merged

**Comment by FirefoxyleGibus** [comment]
I'm trusting that you're a good dev
merging

**Comment by Alekuso** [comment]
> I'm trusting that you're a good dev merging

you shouldn't.

**Pull request merged**
