### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by Alekuso**
This is the first Pull Request of this repo. It contains all the first version of the backend.

Fivx8_PXoAAGVq8

### CODE REVIEW

**Comment by FirefoxyleGibus** [comment]
WHY THE FUCK IS THIS A FOX

**Comment by Alekuso** [comment]
That's u
Fy9sBn_XwAMh7nc

**Comment by Louvtt** [comment]
Stoned_Fox

**Comment by FirefoxyleGibus** [comment]
NO PR FOR YOU

**Comment by Alekuso** [comment]
I can do it anyway.

**Comment by FirefoxyleGibus** [comment]
too late

**Pull request merged**
